### ISSUE TITLE
Feedback Aufgabe 3

### ISSUE THREAD

**Issue by AnnaLotz** [haaseeli/EIA2#2]
- Anwend.diagr. und skizze okay
- Bitte nur ein Konzept hochladen, sonst weiß ich nicht, was ich korrigieren soll
- insgesamt noch ein bisschen zu ungenau, vor allem bei KarteAblegen. Woher weiß das system, welche karte icch geklickt habe?

- Mau Mau ist interaktiv, aber funktioniert nicht ganz richtig:
Ich will eine bestimmte Karte anklicken und genau diese ablegen. Nicht über einen Button die erste karte ablegen!!
- nachdem ich einmal die Karten sortiert habe, werden mir die Karten direkt beim Ziehen sortiert in die Handkarten gelegt
- keinen onclick verwenden!

**Comment by LukasBlea** [comment]
Hey Anna! 
Ich hab die verbesserte Version des Codes hochgeladen. 
Alles wurde gefixt allerdings finde ich absolut keine Informationen oder auch "taktiken", mit denen ich die geklickte Handkarte ablegen kann. Das ist wirklich das einzige Problem welches momentan besteht. Könntest du uns vielleicht eine Hilfestellung bzw einen Tipp dazu geben?
Momentan wirklich verzweifelt und finde absolut keinen Lösungsansatz dazu x.x

**Comment by AnnaLotz** [comment]
Hallo!
Das Problem ist es ja heraus zu finden, welche Karte mit welchem Inhalt geklickt wurde, also wo die Karte im Handarray liegt. Wichtig ist hier die Unterscheidung zwischen den Karten im Array und den angezeigten Karten im Html. Die Html-Seite weiß von sich aus nicht mehr über die einzelnen (Karten-)divs als du ihnen mit gibst. Also nur was für ein Text drin steht und was du ihm für Attribute gegeben hast.
Was das Programm dir bei einem Klick geben kann, sind alle Informationen die dieses bestimmte Element im Html für Attribute und Werte hat (class, id, ...). Das bekommt man über den Übergabeparameter vom Event: `_event: MousEvent` zum Beispiel bei einem Click.
Nun musst du dir Überlegen, wie du dein Html-Div so gestalten kannst, damit du später von diesem aus wieder auf dein Handkarten-Array zurückführen kannst.
Ich hoffe das hilft dir soweit erstmal weiter!

**Comment by LukasBlea** [comment]
Vielen dank für die Hilfestellung, der verbesserte Code ist hochgeladen!
