### ISSUE TITLE
Feedback Aufgabe 4

### ISSUE THREAD

**Issue by AnnaLotz** [haaseeli/EIA2#3]
Konzept:
- Skizze und Anwendungsfalldiagramm sind nicht im finalen Konzept drin. Wenn die nicht in der gleichen Datei sind, zählen sie als nicht abgegeben!
- in AD Events falsch verwendet: diese Sind immer der Start einer Aktivität!
- für jeden case im switch eine einzelne Aktivität zu malen war anstrengend oder? Wenn die Aktivitäten im Prinzip bis auf ein/zwei Variablen gleich sind, wäre dann eine andere Lösung nicht einfacher? (*hust* Funktion mit Übergabeparametern *hust*)
- die Bedingungen an einer Abzweigung bitte genauer/näher an den entsprechenden Pfeil schreiben, damit klar ist, welcher weg wann ausgelöst wird
- ansonsten okay

Anwendung:
- Sinnvolle Wahl der Form-Elemente
- ich kann nicht mehrere Kugeln einer Sorte auswählen :(
- Zusammenfassung klappt
- der Button zur Überprüfung nicht

**Comment by LukasBlea** [comment]
Hey Anna!
Weder Eli noch Ich befinden sich momentan zuhause und wir konnten die PDF mit dem Anwendungsfalldiaramm und der Skizze nicht mit der PDF des AD "verbinden" da wir beide kein Programm außerhalb der Uni besitzen das uns ermöglicht zwei PDF's miteinander zu verbinden (Adobe Acrobat Pro).
Ich hoffe das war/ist nicht allzuschlimm und wir werden und sofort drum kümmern wenn wir wieder in Furtwangen sind.

**Comment by haaseeli** [comment]
Ich dachte ehrlich gesagt, dass die Skizze und das finale Konzept zwei unterschiedliche Abgaben sind und nur das finale Konzept am Sonntag in einem Dokument sein soll... 😅

**Comment by AnnaLotz** [comment]
Hallo ihr zwei,
nochmal zur Klarstellung: alle Punkte, die unter Konzeption bei der Aufgabenstellung gelistet sind, müssen am Ende als ein Dokument abgegeben werden. Heißt auch die überarbeiteten AD's plus Skizze und/oder Anwendungsfalldiagramm, je nachdem was gefragt ist. 
Ich habe schon gesehen, dass ihr da was gemacht habt, aber das war halt in dem ersten Konzept drin, deswegen muss ich das aus reiner Konsequenz als nicht abgegeben zählen :/
Wenn ihr das beim Verteidigen am Donnerstag richtig vorzeigen könnt, ist ja alles gut. Für die Zukunft wisst ihr es jetzt :)
